// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MottFinder.Infrastructure.Data.AppData;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace MottFinder.Migrations
{
    [DbContext(typeof(AppDataContext))]
    partial class AppDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MottFinder.Domain.Entities.Moto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_MOTO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Localizacao")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("DS_LOCALIZACAO");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("NM_MODELO");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(20)")
                        .HasColumnName("ST_MOTO");

                    b.HasKey("Id");

                    b.ToTable("TB_MOTO");
                });
#pragma warning restore 612, 618
        }
    }
}
